# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in business.gemspec
gemspec

gem 'guard-rspec'
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.12'
gem 'rubocop', '~> 1.39'
