# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in business.gemspec
gemspec

gem 'rake', '~> 13.0'

group :development, :test do
  gem 'guard-rspec'
  gem 'rspec', '~> 3.12', require: false
  gem 'rubocop', '~> 1.39', require: false
  gem 'rubocop-rspec', '~> 2.15', require: false
end
