# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'business', path: '../business'
gem 'rake', '~> 13.0'
gem 'rubocop', '~> 1.39', require: false
gem 'webrick'

group :test do
  gem 'guard-rspec'
  gem 'rack-test'
  gem 'rspec', '~> 3.12'
  gem 'rubocop-rspec', require: false
end
