name: Api

on:
  push:
    branches:
      - main

  pull_request:

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.7.0'
          - '3.1.0'
          - '3.2.0'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install latest bundler
      run: |
        gem install bundler --no-document
        bundle config set without 'tools benchmarks docs'
    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
    - name: Run all test
      run: bundle exec rake
